### ISSUE TITLE
Scrolling bar

### ISSUE THREAD

**Issue by bookdude13** [ByronAmbright/Rudolph#14]
Would the scrolling bar be better if we scrolled the grid and kept the bar fixed at the beginning, instead of jumping once we reach the end of the screen? That would be an improvement from Vixen I think...

@theeldestelder thoughts?

**Comment by ByronAmbright** [comment]
There is a scroll to column variable that we can make use of to do this.

**Comment by theeldestelder** [comment]
> scrolled the grid and kept the bar fixed at the beginning

I think there's some potential here.  One issue I see is having the playback be jumpy if we use the scrollToColumn variable (don't know if this is the case - haven't tested it).  Is there any advantage to having the scrolling bar be in one particular area of the screen?  I'm reading your comment as keeping the scrolling bar fixed on the left side of the screen.  Let me know if I'm wrong.

If you're working on a section and want to check if it looks fine in the visualizer, having the part you're interested in at the left side of the screen (and mostly off the screen because it's already scrolled through that part) instead of the middle might make it more difficult to make quick edits because you'd have to scroll back to where you were working every time.  

Thought: Maybe you'd keep the bar in the middle of the screen for the majority of the song while the grid scrolls behind it and have some special cases for the beginning and end of the song where there are no more cells to scroll into.

**Comment by bookdude13** [comment]
That's a good point. I like the idea of middle with special cases.

**Comment by theeldestelder** [comment]
Ok sounds good.  I'll start looking at implementing that.
